tribits_package_define_dependencies(
  LIB_REQUIRED_PACKAGES
    KokkosCore
  LIB_OPTIONAL_PACKAGES
    KokkosKernels
  LIB_REQUIRED_TPLS
    BLAS
    LAPACK
    CUDA
    nanoflann
  LIB_OPTIONAL_TPLS
    MPI
  )
